phpqa:
    tools:
        - php-cs-fixer:0
        - phpstan:0
        - phpunit:0
        - psalm:0
        - security-checker:0
    output: cli

php-cs-fixer:
    config: .php_cs

phpstan:
    level: max
    configuration: phpstan.neon

psalm:
    config: psalm.xml
